Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -3,7 +3,7 @@ pipeline {
 
     environment {
         AWS_REGION = "ap-south-1"
-        AWS_CREDENTIALS = credentials('aws-credentials')  // Ensure you add AWS credentials in Jenkins
+        AWS_CREDENTIALS = credentials('aws-credentials')  // Ensure AWS credentials are added in Jenkins
     }
 
     stages {
@@ -13,9 +13,26 @@ pipeline {
             }
         }
 
+        stage('Install Packer') {
+            steps {
+                sh '''
+                if ! command -v packer &> /dev/null
+                then
+                    echo "Packer not found! Installing..."
+                    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
+                    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
+                    sudo apt update && sudo apt install -y packer
+                    packer --version
+                else
+                    echo "Packer is already installed"
+                fi
+                '''
+            }
+        }
+
         stage('Validate Packer Configuration') {
             steps {
-                sh 'packer validate packer.hcl'
+                sh 'packer validate packer.pkr.hcl'
             }
         }
 
@@ -23,7 +40,7 @@ pipeline {
             steps {
                 sh '''
                 packer init .
-                packer build -var "aws_region=${AWS_REGION}" packer.hcl
+                packer build -var "aws_region=${AWS_REGION}" packer.pkr.hcl
                 '''
             }
         }
